apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: cruiser.dev-ingress
spec:
  entryPoints:
   - web
  routes:
    - match: Host(`cruiser.dev`)
      kind: Rule
      services:
      - name: dot-ops-server
        port: 80

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: cruiser.dev-secure-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`cruiser.dev`)
      services:
        - name: dot-ops-server
          port: 80
  tls:
    secretName: cruiser.dev-tls

---

apiVersion: v1
kind: Service
metadata:
  name: dot-ops-server
spec:
  selector:
    app: dot-ops-server
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dot-ops-server
spec:
  selector:
    matchLabels:
      app: dot-ops-server
  replicas: 1
  template:
    metadata:
      labels:
        app: dot-ops-server
    spec:
      containers:
      - name: dot-ops
        image: harbor.dotglitch.dev/library/dot-ops:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: harbor-key

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cruiser.dev
spec:
  commonName: cruiser.dev
  dnsNames:
    - cruiser.dev
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: cruiser.dev-tls


