apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dev.ci.dotglitch-ingress
spec:
  entryPoints:
   - web
  routes:
    - match: Host(`dev.cruiser.dev`)
      kind: Rule
      services:
      - name: dot-ops
        port: 80

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dev.ci.dotglitch-secure-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`dev.cruiser.dev`)
      services:
        - name: dot-ops
          port: 80
  tls:
    secretName: dev.cruiser.dev-tls

---

apiVersion: v1
kind: Service
metadata:
  name: dot-ops
spec:
  selector:
    app: dot-ops
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dot-ops
spec:
  selector:
    matchLabels:
      app: dot-ops
  replicas: 1
  template:
    metadata:
      labels:
        app: dot-ops
    spec:
      containers:
      - name: dot-ops
        image: harbor.dotglitch.dev/library/dot-ops:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: harbor-key

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev.cruiser.dev
spec:
  commonName: dev.cruiser.dev
  dnsNames:
    - dev.cruiser.dev
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: dev.cruiser.dev-tls


