name: build-agent
on:
  push:
    paths:
    - 'agent/**/*'
    - 'agent.dockerfile'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push
      id:   docker_build
      uses: docker/build-push-action@v4
      with:
        context: ./
        file: ./agent.dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ghcr.io/${{ github.repository }}/dotops-agent:latest,ghcr.io/${{ github.repository }}/dotops-agent:${{ github.sha }}
